import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>My react app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <h2 className="h2">Hello world</h2>
      </section>
    </>
  );
}
